<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>Login Page - Ace Admin</title>

		<meta name="description" content="User login page" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<!-- basic styles -->

		<link href="<?php $this->basePath() ?>/assets/css/bootstrap.min.css" rel="stylesheet" />
		<link rel="stylesheet" href="<?php $this->basePath() ?>/assets/css/font-awesome.min.css" />

		<!--[if IE 7]>
		  <link rel="stylesheet" href="assets/css/font-awesome-ie7.min.css" />
		<![endif]-->

		<!-- page specific plugin styles -->

		<!-- fonts -->

		<link rel="stylesheet" href="<?php $this->basePath() ?>/assets/css/ace-fonts.css" />

		<!-- ace styles -->

		<link rel="stylesheet" href="<?php $this->basePath() ?>/assets/css/ace.min.css" />
		<link rel="stylesheet" href="<?php $this->basePath() ?>/assets/css/ace-rtl.min.css" />
                <link rel="stylesheet" href="<?php $this->basePath() ?>/css/style.css" />
		<!--[if lte IE 8]>
		  <link rel="stylesheet" href="assets/css/ace-ie.min.css" />
		<![endif]-->

		<!-- inline styles related to this page -->

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!--[if lt IE 9]>
		<script src="assets/js/html5shiv.js"></script>
		<script src="assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
        <?php // echo "hello";exit; ?>
	<body class="login-layout login-background" >
		<div class="main-container">
			<div class="main-content">
				<div class="row">
					<div class="col-sm-10 col-sm-offset-1">
						<div class="login-container">
                                                    <div class="center" style="min-height: 85px;">
								<h1>
									<!--<i class="icon-leaf green"></i>-->
									<span class="red"></span>
									<span class="white"></span>
								</h1>
								<h4 class="blue"></h4>
							</div>

							<div class="space-6"></div>

							<div class="position-relative">
								<div id="forgot-box" class="forgot-box visible widget-box no-border">
									<div class="widget-body">
										<div class="widget-main">
											<h4 class="header red lighter bigger">
												<i class="icon-key"></i>
												Retrieve Password
											</h4>

											<div class="space-6"></div>
											<p>
												Enter your email and to receive instructions
											</p>

											<?php
                                                                                        $forgotpasswordform = $this->form;
                                                                                        $forgotpasswordform->setAttribute('action', $this->url('auth/default', array('controller' => 'registration', 'action' => 'forgotten-password')));
                                                                                        $forgotpasswordform->prepare();
                                                                                        echo $this->form()->openTag($forgotpasswordform);                                                                                        
                                                                                        ?>
												<fieldset>
													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<?php echo $this->formRow($forgotpasswordform->get('usr_email')); ?>
															<i class="icon-envelope"></i>
														</span>
													</label>

													<div class="clearfix">
<!--														<button type="button" class="width-35 pull-right btn btn-sm btn-danger">
															<i class="icon-lightbulb"></i>
															Send Me!
														</button>-->
                                                                                                                <?php echo $this->formSubmit($forgotpasswordform->get('submit')); ?>
													</div>
                                                                                                    
												</fieldset>
											<?php 
                                                                                        echo $this->form()->closeTag();
                                                                                         ?>
										</div><!-- /widget-main -->

										<div class="toolbar center">
											<a href="<?php echo $this->url('auth/default', array('controller' => 'index', 'action' => 'login'));?>"  class="back-to-login-link">
												Back to login
												<i class="icon-arrow-right"></i>
											</a>
										</div>
									</div><!-- /widget-body -->
								</div><!-- /forgot-box -->

		
							</div><!-- /position-relative -->
						</div>
					</div><!-- /.col -->
				</div><!-- /.row -->
			</div>
		</div><!-- /.main-container -->

		<!-- basic scripts -->

		<!--[if !IE]> -->

		<script type="text/javascript">
			window.jQuery || document.write("<script src='<?php $this->basePath() ?>/assets/js/jquery-2.0.3.min.js'>"+"<"+"/script>");
		</script>

		<!-- <![endif]-->

		<!--[if IE]>
<script type="text/javascript">
 window.jQuery || document.write("<script src='assets/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
</script>
<![endif]-->

		<script type="text/javascript">
			if("ontouchend" in document) document.write("<script src='<?php $this->basePath() ?>/assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
		</script>

		<!-- inline scripts related to this page -->

		<script type="text/javascript">
			function show_box(id) {
			 jQuery('.widget-box.visible').removeClass('visible');
			 jQuery('#'+id).addClass('visible');
			}
		</script>
	</body>
</html>

