<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>Login Page - Ace Admin</title>

		<meta name="description" content="User login page" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<!-- basic styles -->

		<link href="<?php $this->basePath() ?>/assets/css/bootstrap.min.css" rel="stylesheet" />
		<link rel="stylesheet" href="<?php $this->basePath() ?>/assets/css/font-awesome.min.css" />

		<!--[if IE 7]>
		  <link rel="stylesheet" href="assets/css/font-awesome-ie7.min.css" />
		<![endif]-->

		<!-- page specific plugin styles -->

		<!-- fonts -->

		<link rel="stylesheet" href="<?php $this->basePath() ?>/assets/css/ace-fonts.css" />

		<!-- ace styles -->

		<link rel="stylesheet" href="<?php $this->basePath() ?>/assets/css/ace.min.css" />
		<link rel="stylesheet" href="<?php $this->basePath() ?>/assets/css/ace-rtl.min.css" />
		<link rel="stylesheet" href="<?php $this->basePath() ?>/css/style.css" />

		<!--[if lte IE 8]>
		  <link rel="stylesheet" href="assets/css/ace-ie.min.css" />
		<![endif]-->

		<!-- inline styles related to this page -->

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!--[if lt IE 9]>
		<script src="assets/js/html5shiv.js"></script>
		<script src="assets/js/respond.min.js"></script>
		<![endif]-->
	</head>

	<body class="login-layout login-background">
		<div class="main-container">
			<div class="main-content">
				<div class="row">
					<div class="col-sm-10 col-sm-offset-1">
						<div class="login-container">
                                                    <div class="center" style="min-height: 126px; margin-top:20px; margin-left:-66px">
                                                       <img src="<?php $this->basePath() ?>/img/dashboard_logo.png" >
								<h1>
									<!--<i class="icon-leaf green"></i>-->
									<span class="red"></span>
									<span class="white"></span>
								</h1>
								<h4 class="blue"></h4>
							</div>

							<div class="space-6"></div>

							<div class="position-relative">
								<div id="login-box" class="login-box visible widget-box no-border">
									<div class="widget-body">
										<div class="widget-main">
											<h4 class="header blue lighter bigger">
												<i class="icon-coffee green"></i>
												LOGIN
											</h4>

											<div class="space-6"></div>
                                                                                         
											<?php
                                                                                                            ini_set("display_errors", "1");
                                                                                                        error_reporting(E_ALL & ~E_NOTICE);
                                                                                        if (isset($message) && $message != '') {
                                                                                            ?> <p style="color: red">   <?php echo $message; ?> </p> <?php
                                                                                        }
                                                                                        $form = $this->form;
                                                                                        $form->setAttribute('action', $this->url('auth/default', array('controller' => 'index', 'action' => 'login')));
                                                                                        $form->prepare();

                                                                                        echo $this->form()->openTag($form);
                                                                                        ?>
												<fieldset>
													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
														<?php echo $this->formRow($form->get('usr_name')); ?>	
                                                                                                                    <!--<input type="text" class="form-control" placeholder="Username" />-->
															<i class="icon-user"></i>
														</span>
													</label>

													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
                                                                                                                    
                                                                                                                    <?php echo $this->formRow($form->get('usr_password')); ?>
															<!--<input type="password" class="form-control" placeholder="Password" />-->
															<i class="icon-lock"></i>
														</span>
													</label>

													<div class="space"></div>

													<div class="clearfix">
														<label class="inline">
                                                                                                                    <?php echo $this->formRow($form->get('rememberme')); ?>
															<!--<input type="checkbox" class="ace" />-->
															<span class="lbl"> Remember Me</span>
														</label>

														<!--<button type="button" class="width-35 pull-right btn btn-sm btn-primary">-->
<!--															<i class="icon-key"></i>-->
                                                                                                                        <?php echo $this->formSubmit($form->get('submit')); ?>
															
														<!--</button>-->
                                                                                                            
													</div>

													<div class="space-4"></div>
												</fieldset>
											<?php 
                                                                                        echo $this->form()->closeTag();
                                                                                         ?>


										</div><!-- /widget-main -->

										<div class="toolbar clearfix">
											<div>
												<a href="<?php echo $this->url('auth/default', array('controller' => 'registration', 'action' => 'forgotten-password'));?>" class="forgot-password-link">
													<i class="icon-arrow-left"></i>
													I forgot my password
												</a>
											</div>

										</div>
									</div><!-- /widget-body -->
								</div><!-- /login-box -->
							</div><!-- /position-relative -->
						</div>
					</div><!-- /.col -->
				</div><!-- /.row -->
			</div>
		</div><!-- /.main-container -->

		<!-- basic scripts -->

		<!--[if !IE]> -->

		<script type="text/javascript">
			window.jQuery || document.write("<script src='<?php $this->basePath() ?>/assets/js/jquery-2.0.3.min.js'>"+"<"+"/script>");
		</script>

		<!-- <![endif]-->

		<!--[if IE]>
<script type="text/javascript">
 window.jQuery || document.write("<script src='assets/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
</script>
<![endif]-->

		<script type="text/javascript">
			if("ontouchend" in document) document.write("<script src='<?php $this->basePath() ?>/assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
		</script>

		<!-- inline scripts related to this page -->

		<script type="text/javascript">
			function show_box(id) {
			 jQuery('.widget-box.visible').removeClass('visible');
			 jQuery('#'+id).addClass('visible');
			}
		</script>
	</body>
</html>

