<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Dashboard - Ace Admin</title>

        <meta name="description" content="overview &amp; stats" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <!-- basic styles -->

        <link href="<?php $this->basePath() ?>/assets/css/bootstrap.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="<?php $this->basePath() ?>/assets/css/font-awesome.min.css" />
        <link rel="stylesheet" href="<?php $this->basePath() ?>/css/jquery.tagsinput.css" />
        <link rel="stylesheet" href="<?php $this->basePath() ?>/assets/css/jquery-ui-1.10.3.full.min.css" />
        <link rel="stylesheet" href="<?php $this->basePath() ?>/css/jquery-validation-css/screen.css" />
        <link rel="stylesheet" href="<?php $this->basePath() ?>/css/daterangepicker-bs3.css" />
        <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">


        <!--[if IE 7]>
          <link rel="stylesheet" href="<?php //$this->basePath()   ?>/assets/css/font-awesome-ie7.min.css" />
        <![endif]-->

        <!-- page specific plugin styles -->

        <!-- fonts -->

        <link rel="stylesheet" href="<?php $this->basePath() ?>/assets/css/ace-fonts.css" />
        <!--<link rel="stylesheet" href="<?php $this->basePath() ?>/assets/css/daterangepicker.css" />-->

        <!-- ace styles -->

        <link rel="stylesheet" href="<?php $this->basePath() ?>/assets/css/ace.min.css" />
        <link rel="stylesheet" href="<?php $this->basePath() ?>/assets/css/ace-rtl.min.css" />
        <link rel="stylesheet" href="<?php $this->basePath() ?>/assets/css/ace-skins.min.css" />
        <!--<link rel="stylesheet" href="<?php $this->basePath() ?>/css/style.css" />-->
        <!--[if lte IE 8]>
          <link rel="stylesheet" href="assets/css/ace-ie.min.css" />
        <![endif]-->

        <!-- inline styles related to this page -->

        <!-- ace settings handler -->

        <script src="<?php $this->basePath() ?>/assets/js/ace-extra.min.js"></script>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

        <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.js"></script>
        <script src="assets/js/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
        <?php // print_r($this->layout()->someVar);exit; ?>
        <div class="navbar navbar-default" id="navbar">
            <script type="text/javascript">
                try {
                    ace.settings.check('navbar', 'fixed')
                } catch (e) {
                }
            </script>

            <div class="navbar-container" id="navbar-container">
                <div class="navbar-header pull-left">
                    <a href="<?php $this->basePath() ?>" class="navbar-brand">
                        <small>
                            <img src="<?php $this->basePath() ?>/img/speakeasy_logo.png" >
                        </small>
                    </a><!-- /.brand -->
                </div><!-- /.navbar-header -->

                <div class="navbar-header pull-right" role="navigation">
                    <ul class="nav ace-nav">
                        <li class="grey">
                          <a href="<?php echo $this->url('auth/default', array('controller' => 'index', 'action' => 'logout'));?>"><?php echo $this->translate('Logout'); ?></a>
                        </li>
                        <li class="grey">
                          <a href="<?php echo $this->url('clients', array('controller' => 'index', 'action' => 'list'));?>"><?php echo $this->translate('Clients'); ?></a>
                        </li>
                        <li class="grey">
                          <a href="<?php echo $this->url('auth/default', array('controller' => 'admin', 'action' => 'index'));?>"><?php echo $this->translate('Users'); ?></a>
                        </li>
                        
                    </ul><!-- /.ace-nav -->
                </div><!-- /.navbar-header -->
            </div><!-- /.container -->
        </div>
        <div class="main-container" id="main-container">
            <script type="text/javascript">
                try {
                    ace.settings.check('main-container', 'fixed')
                } catch (e) {
                }
            </script>

            <div class="main-container-inner">
                <a class="menu-toggler" id="menu-toggler" href="#">
                    <span class="menu-text"></span>
                </a>

                <div class="sidebar" id="sidebar">
                    <script type="text/javascript">
                        try {
                            ace.settings.check('sidebar', 'fixed')
                        } catch (e) {
                        }
                    </script>


                    <ul class="nav nav-list">
                        <?php foreach ($this->layout()->someVar as $website) {
                            ?>
                            <li>


                                <a href="/link/index/<?php echo $website->id; ?>" >
                                    <i class="icon-user"></i>
                                    <span class="menu-text"> <?php echo $website->name; ?> </span>
                                </a>
                            </li>
                        <?php } ?>
                    </ul><!-- /.nav-list -->


                </div>

                <div class="main-content">
                    <div class="page-content">                        

                        <div class="row">
                            <div class="col-xs-12">
                                <!-- PAGE CONTENT BEGINS -->

                                <?php echo $this->content; ?>

                                <!-- PAGE CONTENT ENDS -->
                            </div><!-- /.col -->
                        </div><!-- /.row -->
                    </div><!-- /.page-content -->
                </div><!-- /.main-content -->

                <div class="ace-settings-container" id="ace-settings-container">
                    <div class="btn btn-app btn-xs btn-warning ace-settings-btn" id="ace-settings-btn">
                        <i class="icon-cog bigger-150"></i>
                    </div>

                    <div class="ace-settings-box" id="ace-settings-box">
                        <div>
                            <div class="pull-left">
                                <select id="skin-colorpicker" class="hide">
                                    <option data-skin="default" value="#438EB9">#438EB9</option>
                                    <option data-skin="skin-1" value="#222A2D">#222A2D</option>
                                    <option data-skin="skin-2" value="#C6487E">#C6487E</option>
                                    <option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
                                </select>
                            </div>
                            <span>&nbsp; Choose Skin</span>
                        </div>

                        <div>
                            <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-navbar" />
                            <label class="lbl" for="ace-settings-navbar"> Fixed Navbar</label>
                        </div>

                        <div>
                            <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-sidebar" />
                            <label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
                        </div>

                        <div>
                            <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-breadcrumbs" />
                            <label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
                        </div>

                        <div>
                            <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-rtl" />
                            <label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
                        </div>

                        <div>
                            <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-add-container" />
                            <label class="lbl" for="ace-settings-add-container">
                                Inside
                                <b>.container</b>
                            </label>
                        </div>
                    </div>
                </div><!-- /#ace-settings-container -->
            </div><!-- /.main-container-inner -->

            <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
                <i class="icon-double-angle-up icon-only bigger-110"></i>
            </a>
        </div><!-- /.main-container -->

        <!-- basic scripts -->

        <!--[if !IE]> -->

        <script type="text/javascript">
            window.jQuery || document.write("<script src='<?php $this->basePath() ?>/assets/js/jquery-2.0.3.min.js'>" + "<" + "/script>");
        </script>

        <!-- <![endif]-->

        <!--[if IE]>
<script type="text/javascript">
window.jQuery || document.write("<script src='assets/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
</script>
<![endif]-->

        <script type="text/javascript">
            if ("ontouchend" in document)
                document.write("<script src='<?php $this->basePath() ?>/assets/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
        </script>
        <script src="<?php $this->basePath() ?>/assets/js/bootstrap.min.js"></script>
        <script src="<?php $this->basePath() ?>/assets/js/typeahead-bs2.min.js"></script>
        <script src="<?php $this->basePath() ?>/js/jquery.validate.js"></script>
        <script src="<?php $this->basePath() ?>/js/additional-methods.js"></script>

        <!-- page specific plugin scripts -->

        <!-- page specific plugin scripts -->

        <script src="<?php $this->basePath() ?>/assets/js/jquery.dataTables.min.js"></script>
        <script src="<?php $this->basePath() ?>/assets/js/jquery.dataTables.bootstrap.js"></script>
        <!--[if lte IE 8]>
          <script src="assets/js/excanvas.min.js"></script>
        <![endif]-->
        <script src="<?php $this->basePath() ?>/assets/js/jquery-ui-1.10.3.full.min.js"></script>
        <script src="<?php $this->basePath() ?>/assets/js/jquery.ui.touch-punch.min.js"></script>
        <script src="<?php $this->basePath() ?>/assets/js/jquery.maskedinput.min.js"></script>
<!--	<script src="<?php $this->basePath() ?>/assets/js/jquery-ui-1.10.3.custom.min.js"></script>
        <script src="<?php $this->basePath() ?>/assets/js/jquery.ui.touch-punch.min.js"></script>
        <script src="<?php $this->basePath() ?>/assets/js/jquery.slimscroll.min.js"></script>
        <script src="<?php $this->basePath() ?>/assets/js/jquery.easy-pie-chart.min.js"></script>
        <script src="<?php $this->basePath() ?>/assets/js/jquery.sparkline.min.js"></script>
        <script src="<?php $this->basePath() ?>/assets/js/flot/jquery.flot.min.js"></script>
        <script src="<?php $this->basePath() ?>/assets/js/flot/jquery.flot.pie.min.js"></script>
        <script src="<?php $this->basePath() ?>/assets/js/flot/jquery.flot.resize.min.js"></script>-->
        
        <script src="<?php $this->basePath() ?>/js/jquery.tagsinput.js"></script>
        <script src="<?php $this->basePath() ?>/js/moment.js"></script>
        <script src="<?php $this->basePath() ?>/js/daterangepicker.js"></script>
       
        
<!--        <script src="<?php $this->basePath() ?>/assets/js/date-time/daterangepicker.min.js"></script>-->        
<!--            <script src="<?php $this->basePath() ?>/assets/js/chosen.jquery.min.js"></script>
                <script src="<?php $this->basePath() ?>/assets/js/fuelux/fuelux.spinner.min.js"></script>
                <script src="<?php $this->basePath() ?>/assets/js/date-time/bootstrap-datepicker.min.js"></script>
                <script src="<?php $this->basePath() ?>/assets/js/date-time/bootstrap-timepicker.min.js"></script>
                <script src="<?php $this->basePath() ?>/assets/js/date-time/moment.min.js"></script>
                <script src="<?php $this->basePath() ?>/assets/js/date-time/daterangepicker.min.js"></script>
                <script src="<?php $this->basePath() ?>/assets/js/bootstrap-colorpicker.min.js"></script>
                <script src="<?php $this->basePath() ?>/assets/js/jquery.knob.min.js"></script>
                <script src="<?php $this->basePath() ?>/assets/js/jquery.autosize.min.js"></script>
                <script src="<?php $this->basePath() ?>/assets/js/jquery.inputlimiter.1.3.1.min.js"></script>
                <script src="<?php $this->basePath() ?>/assets/js/jquery.maskedinput.min.js"></script>
                <script src="<?php $this->basePath() ?>/assets/js/bootstrap-tag.min.js"></script>-->
        <!-- ace scripts -->

        <script src="<?php $this->basePath() ?>/assets/js/ace-elements.min.js"></script>
        <script src="<?php $this->basePath() ?>/assets/js/ace.min.js"></script>
        <script src="<?php $this->basePath() ?>/js/style.js"></script>
        <!--<script src="<?php $this->basePath() ?>/js/bootstrap-datetimepicker.min.js"></script>-->

        <!-- inline scripts related to this page -->


    </body>
</html>
